# Generated by Django 5.0 on 2023-12-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('imagencategoria', models.BinaryField(null=True)),
                ('catnombre', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('imagenp', models.BinaryField(null=True)),
                ('puntosp', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('codprincipal', models.CharField(max_length=25, null=True)),
                ('nombreproducto', models.CharField(max_length=300)),
                ('descripcionproducto', models.CharField(blank=True, max_length=300, null=True)),
                ('preciounitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('iva', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1)),
                ('ice', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1)),
                ('irbpnr', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposProductos',
            fields=[
                ('id_tipoproducto', models.AutoField(primary_key=True, serialize=False)),
                ('tpnombre', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'tiposproductos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('idum', models.AutoField(primary_key=True, serialize=False)),
                ('nombreum', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'unidadmedida',
                'managed': False,
            },
        ),
    ]
