# Generated by Django 5.0 on 2024-01-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('id_mesa', models.AutoField(primary_key=True, serialize=False)),
                ('observacion', models.CharField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(choices=[('D', 'D'), ('R', 'R'), ('U', 'U'), ('A', 'A')], default='D', max_length=1)),
                ('activa', models.CharField(choices=[('0', '0'), ('1', '1')], default='0', max_length=1)),
                ('maxpersonas', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'mesas',
                'managed': False,
            },
        ),
    ]
