# Generated by Django 5.0 on 2023-12-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id_combo', models.AutoField(primary_key=True, serialize=False)),
                ('imagenc', models.BinaryField(blank=True, null=True)),
                ('puntoscb', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('codprincipal', models.CharField(max_length=25)),
                ('nombrecb', models.CharField(blank=True, max_length=300, null=True)),
                ('descripcioncombo', models.CharField(blank=True, max_length=300, null=True)),
                ('preciounitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('iva', models.CharField(max_length=1)),
                ('ice', models.CharField(max_length=1)),
                ('irbpnr', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'combo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('nombreusuario', models.CharField(max_length=300, unique=True)),
                ('contrasenia', models.CharField()),
                ('fechacreacion', models.DateTimeField()),
                ('fechafin', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=500, null=True)),
                ('fotoperfil', models.BinaryField(blank=True, null=True)),
                ('estadocuenta', models.CharField(max_length=1)),
                ('rol', models.CharField(max_length=1)),
                ('correorecuperacion', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'cuenta',
                'managed': False,
            },
        ),
    ]
