# Generated by Django 5.0 on 2023-12-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasCombos',
            fields=[
                ('id_catcombo', models.AutoField(primary_key=True, serialize=False)),
                ('imagencategoria', models.BinaryField(null=True)),
                ('catnombre', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'categoriascombos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id_combo', models.AutoField(primary_key=True, serialize=False)),
                ('imagenc', models.BinaryField(null=True)),
                ('puntoscb', models.DecimalField(decimal_places=0, max_digits=3, null=True)),
                ('codprincipal', models.CharField(max_length=25)),
                ('nombrecb', models.CharField(max_length=300, null=True)),
                ('descripcioncombo', models.CharField(max_length=300, null=True)),
                ('preciounitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('iva', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1)),
                ('ice', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1)),
                ('irbpnr', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1)),
            ],
            options={
                'db_table': 'combo',
                'managed': False,
            },
        ),
    ]
