# Generated by Django 5.0 on 2023-12-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('srazon_social', models.CharField(max_length=300)),
                ('sruc', models.CharField(max_length=20)),
                ('sestado', models.CharField(max_length=1)),
                ('scapacidad', models.CharField(blank=True, max_length=1, null=True)),
                ('scorreo', models.CharField(max_length=300)),
                ('stelefono', models.CharField(blank=True, max_length=300, null=True)),
                ('sdireccion', models.CharField(max_length=300)),
                ('snombre', models.CharField(blank=True, max_length=300, null=True)),
                ('fsapertura', models.DateField(blank=True, null=True)),
                ('firmaelectronica', models.BinaryField(blank=True, null=True)),
                ('imagensucursal', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sucursales',
                'managed': False,
            },
        ),
    ]
