# Generated by Django 5.0 on 2023-12-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('enombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('etelefono', models.CharField(blank=True, max_length=10, null=True)),
                ('correoelectronico', models.CharField(blank=True, max_length=256, null=True)),
                ('fechafundacion', models.DateField()),
                ('sitioweb', models.CharField(blank=True, max_length=2000, null=True)),
                ('eslogan', models.CharField(blank=True, max_length=300, null=True)),
                ('elogo', models.BinaryField(blank=True, null=True)),
                ('edescripcion', models.CharField(blank=True, max_length=800, null=True)),
                ('docmenu', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
    ]
